### ISSUE TITLE
C# Port ?

### ISSUE THREAD

**Issue by RUSshy** [1vanK/Urho3DSpriteBatch#2]
Hello

I am using C# version of Urho3D from Xamarin

Do you think you can port this spritebatch to C# ?

Thanks <3

**Comment by 1vanK** [comment]
No any plans

**Comment by RUSshy** [comment]
Ok ty for reply, i will try to do it but i am not good at c++

**Comment by 1vanK** [comment]
Ты похоже русский, мб этот туториал поможет тебе https://github.com/1vanK/Urho3DTutor01
